"""
=============================================================
CATALOGO EDUCATIVO Y DICCIONARIO DE SEÑAS LSC
Lengua de Señas Colombiana (LSC)
=============================================================
Metadatos pedagógicos, instrucciones de postura articular,
categorías y consejos prácticos para el aprendizaje interactivo.
"""

from typing import Dict, Any, List

DICCIONARIO_EDUCATIVO_LSC: Dict[str, Dict[str, Any]] = {
    # ── 1. NUMEROS Y CIFRAS ──
    "1": {
        "nombre": "Número 1",
        "categoria": "Números",
        "cuadrante": "ESPACIO_LATERAL",
        "dedos": [0, 1, 0, 0, 0],
        "descripcion": "Dedo índice extendido verticalmente hacia arriba. Los otros cuatro dedos permanecen cerrados en puño con el pulgar sujetándolos.",
        "consejo": "Mantén la muñeca recta y la palma orientada hacia el frente o ligeramente hacia ti.",
        "ejemplo_uso": "Yo tengo 1 hermano.",
    },
    "4": {
        "nombre": "Número 4",
        "categoria": "Números",
        "cuadrante": "ESPACIO_LATERAL",
        "dedos": [0, 1, 1, 1, 1],
        "descripcion": "Los cuatro dedos largos (índice, medio, anular y meñique) extendidos hacia arriba y separados. El pulgar doblado sobre la palma.",
        "consejo": "No abras el pulgar para no confundirlo con el número 5.",
        "ejemplo_uso": "Son las 4 de la tarde.",
    },
    "5": {
        "nombre": "Número 5",
        "categoria": "Números",
        "cuadrante": "ESPACIO_LATERAL",
        "dedos": [1, 1, 1, 1, 1],
        "descripcion": "Todos los cinco dedos completamente extendidos y separados, palma hacia el frente.",
        "consejo": "Abre bien todos los dedos en el espacio neutro.",
        "ejemplo_uso": "Tengo 5 minutos libres.",
    },
    "6": {
        "nombre": "Número 6",
        "categoria": "Números",
        "cuadrante": "ESPACIO_LATERAL",
        "dedos": [1, 1, 1, 1, 0],
        "descripcion": "El pulgar y el dedo meñique se tocan por las yemas formando un arco, mientras que los dedos índice, medio y anular permanecen extendidos.",
        "consejo": "En LSC, el 6 se forma tocando pulgar y meñique.",
        "ejemplo_uso": "Compré 6 manzanas.",
    },
    "7": {
        "nombre": "Número 7",
        "categoria": "Números",
        "cuadrante": "ESPACIO_LATERAL",
        "dedos": [1, 1, 1, 0, 1],
        "descripcion": "El pulgar toca la yema del dedo anular, manteniendo extendidos el índice, medio y meñique.",
        "consejo": "Asegúrate de doblar únicamente el anular contra el pulgar.",
        "ejemplo_uso": "Faltan 7 días para el viaje.",
    },
    "8": {
        "nombre": "Número 8",
        "categoria": "Números",
        "cuadrante": "ESPACIO_LATERAL",
        "dedos": [1, 1, 0, 1, 1],
        "descripcion": "El pulgar toca la yema del dedo medio, manteniendo extendidos el índice, anular y meñique.",
        "consejo": "Dobla firmemente el dedo del corazón con el pulgar.",
        "ejemplo_uso": "La cita es a las 8 de la mañana.",
    },
    "9": {
        "nombre": "Número 9",
        "categoria": "Números",
        "cuadrante": "ESPACIO_LATERAL",
        "dedos": [1, 0, 1, 1, 1],
        "descripcion": "El pulgar toca la yema del dedo índice formando un anillo, mientras que el medio, anular y meñique quedan extendidos hacia arriba.",
        "consejo": "Mantén los tres dedos libres erguidos para no confundir con 'O'.",
        "ejemplo_uso": "El bus número 9.",
    },
    "10": {
        "nombre": "Número 10",
        "categoria": "Números",
        "cuadrante": "ESPACIO_LATERAL",
        "dedos": [1, 0, 0, 0, 0],
        "descripcion": "Mano en puño con el pulgar erguido hacia arriba, realizando un pequeño giro o sacudida de muñeca.",
        "consejo": "El pulgar apunta hacia arriba mientras haces un leve movimiento rotatorio.",
        "ejemplo_uso": "Tengo 10 años.",
    },
    "MIL": {
        "nombre": "Mil (1.000)",
        "categoria": "Números",
        "cuadrante": "ESPACIO_LATERAL",
        "dedos": [1, 1, 1, 0, 0],
        "descripcion": "Configuración manual en forma de 'M' o toque de yemas sobre la palma abierta indicando millares.",
        "consejo": "Movimiento breve hacia adelante.",
        "ejemplo_uso": "Cuesta mil pesos.",
    },
    "MILLON": {
        "nombre": "Millón (1.000.000)",
        "categoria": "Números",
        "cuadrante": "ESPACIO_LATERAL",
        "dedos": [1, 1, 1, 0, 0],
        "descripcion": "Doble toque o desplazamiento acentuado sobre la palma extendida representando un millón.",
        "consejo": "Realiza el movimiento con firmeza.",
        "ejemplo_uso": "Un millón de gracias.",
    },

    # ── 2. SALUDOS Y CORTESIA ──
    "HOLA": {
        "nombre": "Hola",
        "categoria": "Saludos",
        "cuadrante": "CABEZA_ROSTRO",
        "dedos": [1, 1, 1, 1, 1],
        "descripcion": "Mano abierta a la altura de la sien o frente, moviéndose suavemente hacia afuera en señal de saludo cordial.",
        "consejo": "Inicia cerca de la ceja derecha y desplaza hacia la derecha con una leve sonrisa.",
        "ejemplo_uso": "¡Hola a todos!",
    },
    "BUENAS": {
        "nombre": "Buenas",
        "categoria": "Saludos",
        "cuadrante": "ESPACIO_CENTRAL",
        "dedos": [1, 1, 1, 1, 1],
        "descripcion": "Mano abierta sobre el mentón o pecho que se desplaza hacia adelante con la palma hacia arriba.",
        "consejo": "Sirve como base para 'Buenas días', 'Buenas tardes' y 'Buenas noches'.",
        "ejemplo_uso": "Buenas tardes.",
    },
    "DIAS": {
        "nombre": "Días",
        "categoria": "Saludos",
        "cuadrante": "ESPACIO_CENTRAL",
        "dedos": [1, 1, 0, 0, 0],
        "descripcion": "Dedo índice extendido apuntando hacia arriba representando la salida del sol.",
        "consejo": "Combínalo con 'BUENAS' para formar '¡Buenos días!'.",
        "ejemplo_uso": "Buenos días profesor.",
    },
    "TARDES": {
        "nombre": "Tardes",
        "categoria": "Saludos",
        "cuadrante": "ESPACIO_CENTRAL",
        "dedos": [1, 1, 1, 1, 1],
        "descripcion": "Brazo extendido horizontalmente con la mano bajando suavemente simulando el atardecer.",
        "consejo": "Movimiento descendente pausado.",
        "ejemplo_uso": "Buenas tardes compañeros.",
    },
    "NOCHES": {
        "nombre": "Noches",
        "categoria": "Saludos",
        "cuadrante": "ESPACIO_CENTRAL",
        "dedos": [1, 1, 1, 1, 1],
        "descripcion": "La mano dominante pasa por encima del brazo opuesto cubriéndolo, simulando la puesta del sol y la noche.",
        "consejo": "Movimiento envolvente hacia abajo.",
        "ejemplo_uso": "Buenas noches que descanses.",
    },
    "BIENVENIDO": {
        "nombre": "Bienvenido",
        "categoria": "Saludos",
        "cuadrante": "ESPACIO_CENTRAL",
        "dedos": [1, 1, 1, 1, 1],
        "descripcion": "Ambas manos abiertas con las palmas hacia arriba, acercándose hacia el pecho en gesto acogedor.",
        "consejo": "Gesto abierto y hospitalario hacia la persona.",
        "ejemplo_uso": "Bienvenido a Colombia.",
    },
    "BIEN": {
        "nombre": "Bien / Todo bien",
        "categoria": "Saludos",
        "cuadrante": "ESPACIO_CENTRAL",
        "dedos": [1, 0, 0, 0, 0],
        "descripcion": "Mano en puño con el pulgar hacia arriba o mano saliendo del mentón hacia adelante con energía positiva.",
        "consejo": "Acompaña con expresión facial asertiva.",
        "ejemplo_uso": "Estoy muy bien.",
    },

    # ── 3. PERSONAS, COMUNICACION Y NECESIDADES ──
    "YO": {
        "nombre": "Yo",
        "categoria": "Pronombres",
        "cuadrante": "PECHO_TORSO",
        "dedos": [0, 1, 0, 0, 0],
        "descripcion": "Dedo índice apuntando directamente hacia el centro de tu propio pecho.",
        "consejo": "Toca suavemente tu esternón con la yema del índice.",
        "ejemplo_uso": "Yo quiero aprender LSC.",
    },
    "NOMBRE": {
        "nombre": "Nombre / Llamarse",
        "categoria": "Identidad",
        "cuadrante": "PECHO_TORSO",
        "dedos": [0, 1, 1, 0, 0],
        "descripcion": "Dedos índice y medio extendidos en 'U' o 'H', rozando el pecho o la mano contraria de forma horizontal.",
        "consejo": "Usado para decir 'Mi nombre es...' o preguntar '¿Cómo te llamas?'.",
        "ejemplo_uso": "Mi nombre es Camila.",
    },
    "AYUDAR": {
        "nombre": "Ayudar / Ayuda",
        "categoria": "Emergencia",
        "cuadrante": "ESPACIO_CENTRAL",
        "dedos": [1, 0, 0, 0, 0],
        "descripcion": "Mano en puño con pulgar arriba descansando sobre la palma plana de la otra mano, moviéndose hacia adelante.",
        "consejo": "Si va hacia ti significa 'Ayúdame'; si va hacia el otro significa 'Te ayudo'.",
        "ejemplo_uso": "Por favor ayúdame.",
    },
    "APOYAR": {
        "nombre": "Apoyar / Apoyo",
        "categoria": "Solidaridad",
        "cuadrante": "ESPACIO_CENTRAL",
        "dedos": [1, 0, 0, 0, 0],
        "descripcion": "Ambos puños con pulgares firmes colocándose uno detrás del otro o levantándose mutuamente.",
        "consejo": "Expresa respaldo y acompañamiento.",
        "ejemplo_uso": "Yo te apoyo en tu proyecto.",
    },
    "BAÑO": {
        "nombre": "Baño / Sanitario",
        "categoria": "Emergencia",
        "cuadrante": "ESPACIO_CENTRAL",
        "dedos": [1, 0, 0, 0, 0],
        "descripcion": "Mano en configuración 'T' o puño sacudiéndose suavemente de lado a lado.",
        "consejo": "Seña indispensable en lugares públicos.",
        "ejemplo_uso": "¿Dónde queda el baño?",
    },
    "GUSTAR": {
        "nombre": "Gustar",
        "categoria": "Emociones",
        "cuadrante": "PECHO_TORSO",
        "dedos": [1, 1, 1, 1, 1],
        "descripcion": "Mano abierta sobre el pecho frotando en círculos con agrado.",
        "consejo": "Expresión facial alegre.",
        "ejemplo_uso": "Me gusta la música.",
    },
    "LICOR": {
        "nombre": "Licor / Bebida",
        "categoria": "Vida Diaria",
        "cuadrante": "CUELLO_GARGANTA",
        "dedos": [1, 0, 0, 0, 1],
        "descripcion": "Mano en forma de 'Y' (pulgar y meñique) acercándose a la boca o cuello simulando beber.",
        "consejo": "Movimiento breve hacia la barbilla.",
        "ejemplo_uso": "No tomo licor.",
    },
    "ANNOS": {
        "nombre": "Años / Edad",
        "categoria": "Identidad",
        "cuadrante": "ESPACIO_LATERAL",
        "dedos": [1, 0, 0, 0, 0],
        "descripcion": "Puño rotando alrededor del otro puño o rozando la barbilla para indicar edad.",
        "consejo": "Se acompaña del número de años.",
        "ejemplo_uso": "Tengo 20 años.",
    },

    # ── 4. ALFABETO DACTILOLOGICO (A-Z) ──
    "A": {"nombre": "Letra A", "categoria": "Alfabeto", "cuadrante": "ESPACIO_LATERAL", "dedos": [1, 0, 0, 0, 0], "descripcion": "Puño cerrado con los cuatro dedos flexionados y el pulgar erguido descansando contra el lateral del índice.", "consejo": "El pulgar no debe cruzar sobre los dedos.", "ejemplo_uso": "A de Agua."},
    "B": {"nombre": "Letra B", "categoria": "Alfabeto", "cuadrante": "ESPACIO_LATERAL", "dedos": [0, 1, 1, 1, 1], "descripcion": "Cuatro dedos extendidos juntos hacia arriba. El pulgar doblado sobre la palma.", "consejo": "Mantén los 4 dedos bien unidos.", "ejemplo_uso": "B de Bien."},
    "C": {"nombre": "Letra C", "categoria": "Alfabeto", "cuadrante": "ESPACIO_LATERAL", "dedos": [1, 1, 1, 1, 1], "descripcion": "Todos los dedos y el pulgar curvados formando la letra 'C'.", "consejo": "Curva la mano lateralmente como sosteniendo un vaso.", "ejemplo_uso": "C de Casa."},
    "D": {"nombre": "Letra D", "categoria": "Alfabeto", "cuadrante": "ESPACIO_LATERAL", "dedos": [1, 1, 0, 0, 0], "descripcion": "Dedo índice extendido hacia arriba. El pulgar toca las yemas del medio y anular formando un círculo.", "consejo": "Solo el índice debe quedar erguido.", "ejemplo_uso": "D de Día."},
    "E": {"nombre": "Letra E", "categoria": "Alfabeto", "cuadrante": "ESPACIO_LATERAL", "dedos": [0, 0, 0, 0, 0], "descripcion": "Todos los dedos doblados hacia adentro con las puntas tocando el pulgar doblado en la base.", "consejo": "Las uñas quedan visibles hacia el frente.", "ejemplo_uso": "E de Ejemplo."},
    "F": {"nombre": "Letra F", "categoria": "Alfabeto", "cuadrante": "ESPACIO_LATERAL", "dedos": [1, 1, 1, 1, 1], "descripcion": "El pulgar y el índice se tocan por las yemas formando un círculo; los otros tres dedos quedan erguidos y separados.", "consejo": "Similar al gesto de 'OK'.", "ejemplo_uso": "F de Familia."},
    "G": {"nombre": "Letra G", "categoria": "Alfabeto", "cuadrante": "ESPACIO_LATERAL", "dedos": [1, 1, 0, 0, 0], "descripcion": "Dedo índice y pulgar paralelos apuntando horizontalmente hacia un lado.", "consejo": "Mano orientada de perfil.", "ejemplo_uso": "G de Gracias."},
    "H": {"nombre": "Letra H", "categoria": "Alfabeto", "cuadrante": "ESPACIO_LATERAL", "dedos": [1, 1, 1, 0, 0], "descripcion": "Dedos índice y medio extendidos juntos horizontalmente, con el pulgar sosteniendo los otros dos dedos.", "consejo": "Dedos juntos apuntando hacia el lateral.", "ejemplo_uso": "H de Hola."},
    "I": {"nombre": "Letra I", "categoria": "Alfabeto", "cuadrante": "ESPACIO_LATERAL", "dedos": [0, 0, 0, 0, 1], "descripcion": "Solo el dedo meñique erguido verticalmente; los demás dedos cerrados en puño con el pulgar sujetándolos.", "consejo": "Mantén el meñique bien firme.", "ejemplo_uso": "I de Igualdad."},
    "J": {"nombre": "Letra J", "categoria": "Alfabeto", "cuadrante": "ESPACIO_LATERAL", "dedos": [0, 0, 0, 0, 1], "descripcion": "Misma postura de la 'I' (meñique arriba), dibujando una curva en forma de 'J' en el aire.", "consejo": "Movimiento curvo hacia abajo y arriba.", "ejemplo_uso": "J de Joven."},
    "K": {"nombre": "Letra K", "categoria": "Alfabeto", "cuadrante": "ESPACIO_LATERAL", "dedos": [1, 1, 1, 0, 0], "descripcion": "Dedos índice y medio en 'V' hacia arriba, con el pulgar colocado entre ambos tocando el nudillo del medio.", "consejo": "El pulgar se intercala entre el índice y medio.", "ejemplo_uso": "K de Kilo."},
    "L": {"nombre": "Letra L", "categoria": "Alfabeto", "cuadrante": "ESPACIO_LATERAL", "dedos": [1, 1, 0, 0, 0], "descripcion": "Dedo índice hacia arriba y pulgar extendido a 90 grados formando una 'L'. Los otros 3 dedos cerrados.", "consejo": "Forma clara de 'L' visible para el receptor.", "ejemplo_uso": "L de LSC."},
    "M": {"nombre": "Letra M", "categoria": "Alfabeto", "cuadrante": "ESPACIO_LATERAL", "dedos": [1, 1, 1, 1, 0], "descripcion": "Tres dedos (índice, medio, anular) doblados hacia abajo sobre el pulgar que asoma entre el anular y meñique.", "consejo": "Representa las 3 patas de la letra M.", "ejemplo_uso": "M de Mano."},
    "N": {"nombre": "Letra N", "categoria": "Alfabeto", "cuadrante": "ESPACIO_LATERAL", "dedos": [1, 1, 1, 0, 0], "descripcion": "Dos dedos (índice y medio) doblados hacia abajo sobre el pulgar que asoma entre el medio y anular.", "consejo": "Representa las 2 patas de la letra N.", "ejemplo_uso": "N de Noche."},
    "NN": {"nombre": "Letra Ñ", "categoria": "Alfabeto", "cuadrante": "ESPACIO_LATERAL", "dedos": [1, 1, 1, 0, 0], "descripcion": "Misma postura de la 'N', realizando una pequeña ondulación de muñeca de izquierda a derecha (la virgulilla ~).", "consejo": "Ondulación breve y clara.", "ejemplo_uso": "Ñ de Ñame."},
    "O": {"nombre": "Letra O", "categoria": "Alfabeto", "cuadrante": "ESPACIO_LATERAL", "dedos": [1, 1, 1, 1, 1], "descripcion": "Todos los dedos y el pulgar se tocan por las puntas formando un círculo perfecto.", "consejo": "Forma una 'O' redondeada.", "ejemplo_uso": "O de Ojo."},
    "P": {"nombre": "Letra P", "categoria": "Alfabeto", "cuadrante": "ESPACIO_LATERAL", "dedos": [1, 1, 1, 0, 0], "descripcion": "Postura similar a la 'K', pero orientada hacia abajo con el índice horizontal y el medio apuntando al suelo.", "consejo": "Giro de muñeca apuntando hacia abajo.", "ejemplo_uso": "P de País."},
    "Q": {"nombre": "Letra Q", "categoria": "Alfabeto", "cuadrante": "ESPACIO_LATERAL", "dedos": [1, 1, 0, 0, 0], "descripcion": "Dedo índice y pulgar apuntando hacia abajo con un pequeño espacio entre ellos, como una 'G' hacia el suelo.", "consejo": "Muñeca hacia abajo.", "ejemplo_uso": "Q de Queso."},
    "R": {"nombre": "Letra R", "categoria": "Alfabeto", "cuadrante": "ESPACIO_LATERAL", "dedos": [0, 1, 1, 0, 0], "descripcion": "Dedo medio cruzado por encima del dedo índice hacia arriba. Pulgar sujeta los otros dos dedos.", "consejo": "Cruza los dos dedos como pidiendo un deseo.", "ejemplo_uso": "R de Respeto."},
    "S": {"nombre": "Letra S", "categoria": "Alfabeto", "cuadrante": "ESPACIO_LATERAL", "dedos": [0, 0, 0, 0, 0], "descripcion": "Puño completamente cerrado con el pulgar cruzado por encima del frente de los cuatro dedos doblados.", "consejo": "Diferente de la 'A', aquí el pulgar abraza los dedos por delante.", "ejemplo_uso": "S de Sol."},
    "T": {"nombre": "Letra T", "categoria": "Alfabeto", "cuadrante": "ESPACIO_LATERAL", "dedos": [1, 0, 0, 0, 0], "descripcion": "Puño con el pulgar intercalado entre el dedo índice y el dedo medio.", "consejo": "El pulgar asoma entre índice y medio.", "ejemplo_uso": "T de Tarde."},
    "U": {"nombre": "Letra U", "categoria": "Alfabeto", "cuadrante": "ESPACIO_LATERAL", "dedos": [0, 1, 1, 0, 0], "descripcion": "Dedos índice y medio extendidos juntos hacia arriba sin separación entre ellos.", "consejo": "Mantén los dos dedos pegados.", "ejemplo_uso": "U de Uno."},
    "V": {"nombre": "Letra V", "categoria": "Alfabeto", "cuadrante": "ESPACIO_LATERAL", "dedos": [0, 1, 1, 0, 0], "descripcion": "Dedos índice y medio extendidos hacia arriba en forma de 'V' separados.", "consejo": "Separa los dedos formando la V de la victoria.", "ejemplo_uso": "V de Voz."},
    "W": {"nombre": "Letra W", "categoria": "Alfabeto", "cuadrante": "ESPACIO_LATERAL", "dedos": [0, 1, 1, 1, 0], "descripcion": "Tres dedos (índice, medio, anular) extendidos hacia arriba y separados formando una 'W'.", "consejo": "Pulgar sostiene el meñique.", "ejemplo_uso": "W de Web."},
    "X": {"nombre": "Letra X", "categoria": "Alfabeto", "cuadrante": "ESPACIO_LATERAL", "dedos": [0, 1, 0, 0, 0], "descripcion": "Dedo índice doblado en forma de gancho hacia arriba, los demás dedos cerrados en puño.", "consejo": "Curva el índice como un pequeño anzuelo.", "ejemplo_uso": "X de Xilófono."},
    "Y": {"nombre": "Letra Y", "categoria": "Alfabeto", "cuadrante": "ESPACIO_LATERAL", "dedos": [1, 0, 0, 0, 1], "descripcion": "Pulgar y meñique completamente extendidos hacia los lados; índice, medio y anular cerrados.", "consejo": "Similar al gesto hawaiano 'shaka'.", "ejemplo_uso": "Y de Yema."},
    "Z": {"nombre": "Letra Z", "categoria": "Alfabeto", "cuadrante": "ESPACIO_LATERAL", "dedos": [0, 1, 0, 0, 0], "descripcion": "Dedo índice extendido dibujando la letra 'Z' en el aire con un trazo fluido.", "consejo": "Traza horizontal, diagonal y horizontal.", "ejemplo_uso": "Z de Zapato."},
}


def obtener_catalogo_completo() -> List[Dict[str, Any]]:
    """Retorna la lista completa de señas con metadatos estructurados."""
    catalogo = []
    for codigo, info in DICCIONARIO_EDUCATIVO_LSC.items():
        catalogo.append({
            "id": codigo,
            **info
        })
    return catalogo
